# Generated by Django 3.0.4 on 2020-04-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='futsalinfo',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='futsal/gallery'),
        ),
        migrations.AddField(
            model_name='futsalinfo',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='futsal/gallery'),
        ),
        migrations.AddField(
            model_name='futsalinfo',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='futsal/gallery'),
        ),
        migrations.AddField(
            model_name='futsalinfo',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='futsal/gallery'),
        ),
    ]
