# Generated by Django 3.0.4 on 2020-04-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200410_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futsalinfo',
            name='close_at',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='futsalinfo',
            name='open_at',
            field=models.TimeField(),
        ),
    ]
