# Generated by Django 3.0.4 on 2020-04-12 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('booked_date', models.DateField()),
                ('booked_time', models.TimeField()),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.CharField(default=None, max_length=20)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('booked_futsal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.FutsalInfo')),
            ],
        ),
    ]
